@baseUrl = http://localhost:3000/api


# Datas

# @name getDatas

GET  {{baseUrl}}/datas

###

# @name addNewData

POST {{baseUrl}}/datas
Content-Type: application/json

{
    "name" : "data post"
}

###

#  @name editData

PATCH {{baseUrl}}/datas/2
Content-Type: application/json

{
    "name": "New data"
}

###

#  @name deleteData

DELETE http://localhost:3000/api/datas/2

